name: Workflow / Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy documentsation
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Check out Repo
        uses: actions/checkout@v5
      - name: ğŸ­ Configure Git Credentials
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: âš™ï¸ Make cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: âš™ï¸ Cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: ğŸ“¦ Install mkDocs
        run: pip install mkdocs-material
      - name: ğŸ’… Deploy documentsation
        run: mkdocs gh-deploy --force --config-file .mkdocs.yml
